### ISSUE TITLE
fetch --nohooks --no-history chromium fails when downloading the source code

### ISSUE THREAD

**Issue by ManirajDeivendran** [shawnanastasio/chromium_power#11]
Hi @shawnanastasio , @leo-lb ,

The environment is ppc64le/UBI latest (RHEL based container environment).

Get chromium source code by following the below commands,
cd $HOME
mkdir chromium_build
export CHROMIUM_DIR=$HOME/chromium_build
cd $CHROMIUM_DIR

#GN
git clone https://gn.googlesource.com/gn
export CC=gcc
export CXX=g++
export AR=ar
cd gn/
python build/gen.py --no-static-libstdc++
ninja -C out
unset CXX
unset CC
unset AR 

#Depot tools
cd $CHROMIUM_DIR
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export DEPOT_TOOLS_UPDATE=0
export PATH=${CHROMIUM_DIR}/gn/out:$PATH:${CHROMIUM_DIR}/depot_tools
export VPYTHON_BYPASS="manually managed python not supported by chrome operations"
export GYP_DEFINES="disable_nacl=1"

#Downloading the source code
cd $CHROMIUM_DIR
mkdir chromium && cd chromium
fetch --no-history --nohooks chromium

Facing below issues when execute the command "gclient sync --nohooks --no-history"
```
0:07:24]   src/third_party/angle/third_party/VK-GL-CTS/src
Syncing projects:  96% (124/128) src/third_party/angle/third_party/VK-GL-CTS/src
src/third_party/wayland/src (ERROR)
----------------------------------------
[0:00:05] Started.
[0:00:05]
________ running 'git init --bare /root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud' in '/root/chromium_build/chromium'
[0:00:06] Initialized empty Git repository in /root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud/
[0:00:06]
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/anongit.freedesktop.org/git/wayland/wayland.git --template=/root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud /root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_' in '/root/chromium_build/chromium'
[0:00:06] Cloning into '/root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_'...
[0:00:06] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:06] fatal: the remote end hung up unexpectedly
[0:00:07]
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/anongit.freedesktop.org/git/wayland/wayland.git --template=/root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud /root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_' in '/root/chromium_build/chromium' attempt 2 / 4
[0:00:07] Cloning into '/root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_'...
[0:00:07] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:07] fatal: the remote end hung up unexpectedly
[0:00:08]
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/anongit.freedesktop.org/git/wayland/wayland.git --template=/root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud /root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_' in '/root/chromium_build/chromium' attempt 3 / 4
[0:00:08] Cloning into '/root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_'...
[0:00:09] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:09] fatal: the remote end hung up unexpectedly
[0:00:11]
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/anongit.freedesktop.org/git/wayland/wayland.git --template=/root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud /root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_' in '/root/chromium_build/chromium' attempt 4 / 4
[0:00:11] Cloning into '/root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_'...
[0:00:11] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:11] fatal: the remote end hung up unexpectedly
Traceback (most recent call last):
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 1049, in _Clone
    print_stdout=print_stdout, filter_fn=filter_fn)
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 1388, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/root/chromium_build/depot_tools/gclient_utils.py", line 673, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), command_output.getvalue(), None)
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/anongit.freedesktop.org/git/wayland/wayland.git --template=/root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud /root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_' returned non-zero exit status 128 in /root/chromium_build/chromium
[0:00:15] _____ Conflicting directory found in /root/chromium_build/chromium/src/third_party/wayland/src. Moving to /root/chromium_build/chromium/_bad_scm/src/third_party/wayland/srcwobif1g1.
----------------------------------------
Warnings:
Conflicting directory /root/chromium_build/chromium/src/third_party/wayland/src moved to /root/chromium_build/chromium/_bad_scm/src/third_party/wayland/srcwobif1g1.
Traceback (most recent call last):
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 548, in update
    self._Clone(revision, url, options)
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 1049, in _Clone
    print_stdout=print_stdout, filter_fn=filter_fn)
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 1388, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/root/chromium_build/depot_tools/gclient_utils.py", line 673, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), command_output.getvalue(), None)
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/anongit.freedesktop.org/git/wayland/wayland.git --template=/root/chromium_build/chromium/src/third_party/wayland/_gclient_gittmp_srcvf0ei1ud /root/chromium_build/chromium/src/third_party/wayland/_gclient_src_vhzhe3z_' returned non-zero exit status 128 in /root/chromium_build/chromium

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/root/chromium_build/chromium/src/third_party/wayland/src' -> '/root/chromium_build/chromium/_bad_scm/src/third_party/wayland/srcwobif1g1/src'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chromium_build/depot_tools/metrics.py", line 291, in print_notice_and_exit
    yield
  File "/root/chromium_build/depot_tools/gclient.py", line 3229, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/chromium_build/depot_tools/gclient.py", line 3215, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/root/chromium_build/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/root/chromium_build/depot_tools/gclient.py", line 2769, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/root/chromium_build/depot_tools/gclient.py", line 1809, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "/root/chromium_build/depot_tools/gclient_utils.py", line 967, in flush
    reraise(e[0], e[1], e[2])
  File "/root/chromium_build/depot_tools/gclient_utils.py", line 67, in reraise
    raise value
  File "/root/chromium_build/depot_tools/gclient_utils.py", line 1044, in run
    self.item.run(*self.args, **self.kwargs)
  File "/root/chromium_build/depot_tools/gclient.py", line 945, in run
    file_list)
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 132, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 550, in update
    self._DeleteOrMove(options.force)
  File "/root/chromium_build/depot_tools/gclient_scm.py", line 207, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "/usr/lib64/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib64/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/root/chromium_build/chromium/src/third_party/wayland/src'
```

Tried the workaround mentioned in link https://bugs.chromium.org/p/chromium/issues/detail?id=1167108 (https://bugs.chromium.org/p/chromium/issues/detail?id=1226496). Unfortunately, the workaround doesn't work for me. 

Any pointers help would be great, thanks in advance!!

**Comment by ManirajDeivendran** [comment]
Removing (--no-history) option resolves the issue.
