### ISSUE TITLE
Python UnicodeDecodeError while applying patches

### ISSUE THREAD

**Issue by lysannef** [shawnanastasio/chromium_power#5]
Hi @shawnanastasio ,

I have been using @leo-lb [electron fork](https://github.com/leo-lb/electron/tree/ppc64le-6-1-x) for the build of electron.
I have encountered the following error while running the gclient sync , at the step where it tries to apply all the patches using the cpf.py script file.

```
Running hooks:   3% ( 3/81) patch_chromium
________ running 'bash -c cd src/electron/patches/common/chromium_power && python3 cpf.py ../../../../' in '/electron-gn'
[+] Applying "breakpad/0001-Implement-ppc64-support-on-linux.patch"... Success
[+] Applying "crashpad/0001-Implement-support-for-PPC64-on-Linux.patch"... Traceback (most recent call last):
  File "cpf.py", line 360, in <module>
    main()
  File "cpf.py", line 217, in main
    run_patcher()
  File "cpf.py", line 250, in run_patcher
    apply_patch(dest_dir, patch_path, dry=DRY)
  File "cpf.py", line 95, in apply_patch
    patch_data = f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9031: ordinal not in range(128)
Error: Command 'bash -c cd src/electron/patches/common/chromium_power && python3 cpf.py ../../../../' returned non-zero exit status 1 in /electron-gn
```

Investigated a bit and found that an additional parameter (encoding=utf-8) added to the open functions in the file , i.e. following code :
```
 94     with open(patch_path, "r") as f:
 95         patch_data = f.read()
 96
 97     files = re.findall("^--- a/(.*)", patch_data, re.MULTILINE)
 98     files = [directory + "/" + x for x in files]
 99
100     for fil in files:
101         try:
102            with open(fil, "r") as f:
```

as such:
```
 94     with open(patch_path, "r", encoding="utf-8") as f:
 95         patch_data = f.read()
 96
 97     files = re.findall("^--- a/(.*)", patch_data, re.MULTILINE)
 98     files = [directory + "/" + x for x in files]
 99
100     for fil in files:
101         try:
102            with open(fil, "r", encoding="utf-8") as f
```

 **fixes the issue and all the patches get applied.**

Kindly let me know if I am missing anything or if this could be added as a change in cpf.py

**Comment by llebout** [comment]
@lysannef Hello, which branch did you checkout?
I remember encountering this issue and fixed it by changing my default locale (?)

**Comment by lysannef** [comment]
@leo-lb  Checked out the ppc64le-6-1-x branch. Will try changing my locale and check.

**Comment by lysannef** [comment]
@leo-lb Changing the locale fixed the issue . Thanks !
Closing issue.
