### ISSUE TITLE
clang error:  Unknown command line argument '--enable-global-merge=false'.

### ISSUE THREAD

**Issue by flynn1973** [shawnanastasio/chromium_power#6]
any ideas? seems that this option was renamed in clang to mno-global-merge.

root@lpgaixmgmtlx01:/scratch/chromium_build/chromium/src>clang --help | grep merge
  -fmerge-all-constants   Allow merging of constants
  -fno-merge-all-constants
  -mglobal-merge          Enable merging of globals
  -mno-global-merge       Disable merging of globals

````
root@lpgaixmgmtlx01:/scratch/chromium_build/chromium/src>ninja -C out/Default chrome
ninja: Entering directory `out/Default'
[1127/34585] CXX obj/third_party/angle/src/libANGLE/renderer/vulkan/angle_vulkan_backend/MemoryObjectVk.o
FAILED: obj/third_party/angle/src/libANGLE/renderer/vulkan/angle_vulkan_backend/MemoryObjectVk.o
../../../../llvm_build/bin/clang++ -MMD -MF obj/third_party/angle/src/libANGLE/renderer/vulkan/angle_vulkan_backend/MemoryObjectVk.o.d -DANGLE_VK_LAYERS_DIR=\"angledata\" -DANGLE_VK_MOCK_ICD_JSON=\"angledata/VkICD_mock_icd.json\" -DANGLE_VK_SWIFTSHADER_ICD_JSON=\"./vk_swiftshader_icd.json\" -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_VULKAN -DANGLE_ENABLE_SWIFTSHADER -DANGLE_USE_CUSTOM_VULKAN_CMD_BUFFERS=1 -DLIBANGLE_IMPLEMENTATION -DANGLE_USE_X11 -DVK_USE_PLATFORM_XCB_KHR -DANGLE_ENABLE_OPENGL -DANGLE_ENABLE_OPENGL_NULL -DANGLE_ENABLE_NULL -DANGLE_ENABLE_VULKAN -DANGLE_ENABLE_SWIFTSHADER -DANGLE_USE_CUSTOM_VULKAN_CMD_BUFFERS=1 -I../../third_party/angle/include -I../../third_party/angle/src -I../../third_party/angle/src/common/third_party/base -Igen/angle -I../../third_party/angle/include -I../../third_party/angle/src/third_party/volk -I../../third_party/angle/third_party/vulkan-headers/src/include -I../../third_party/angle/include -I../../third_party/angle/src -I../../third_party/angle/include -I../../third_party/angle/src -I../../third_party/SPIRV-Tools/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-misleading-indentation -Wno-range-loop-analysis -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -Wconditional-uninitialized -Wextra-semi-stmt -Wfloat-conversion -Winconsistent-missing-destructor-override -Wmissing-field-initializers -Wnon-virtual-dtor -Wredundant-parens -Wshadow-field -Wtautological-type-limit-compare -Wundefined-reinterpret-cast -Wunneeded-internal-declaration -Wparentheses -Wrange-loop-analysis -Wstrict-prototypes -Wunreachable-code -Wshorten-64-to-32 -Xclang -mllvm -Xclang --enable-global-merge=false -std=c++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -c ../../third_party/angle/src/libANGLE/renderer/vulkan/MemoryObjectVk.cpp -o obj/third_party/angle/src/libANGLE/renderer/vulkan/angle_vulkan_backend/MemoryObjectVk.o
clang (LLVM option parsing): Unknown command line argument '--enable-global-merge=false'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--enable-tail-merge=false'?
[1144/34585] CXX obj/third_party/angle/libGLESv2/entry_points_gles_ext_autogen.o
ninja: build stopped: subcommand failed.
````

**Comment by llebout** [comment]
Which version of Chromium are you trying to build?
Which version of Clang are you using? Did you compile it from the clang/llvm's commit hash included in Chromium tree? Google only ever supports builds with that specific commit hash, so if you have a problem, use that commit hash.

**Comment by flynn1973** [comment]
clang version is 11.0.0...its from the projects master branch.
not sure about the chrome version, its what the fetch command downloaded. i have no clue how to query the version before compilation.
one new perversity came up, it would seem there are (X86) prebuilt binaries in the source code...i get occassional "wrong exec format" errors during build.

````
[3704/20291] ACTION //third_party/blink/renderer/bindings:generate_bindings_enumeration(//build/toolchain/linux:clang_ppc64)
FAILED:
...
python ../../third_party/blink/renderer/bindings/scripts/generate_bindings.py enumeration --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../ --root_gen_dir gen --output_core_reldir third_party/blink/renderer/bindings/core/v8/ --output_modules_reldir third_party/blink/renderer/bindings/modules/v8/
Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 76, in <module>
    main()
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 72, in main
    dispatch_table[task](web_idl_database=web_idl_database)
  File "/scratch/chromium_build/chromium/src/third_party/blink/renderer/bindings/scripts/bind_gen/enumeration.py", line 343, in generate_enumerations
    generate_enumeration(enumeration)
  File "/scratch/chromium_build/chromium/src/third_party/blink/renderer/bindings/scripts/bind_gen/enumeration.py", line 337, in generate_enumeration
    write_code_node_to_file(header_node, path_manager.gen_path_to(header_path))
  File "/scratch/chromium_build/chromium/src/third_party/blink/renderer/bindings/scripts/bind_gen/codegen_utils.py", line 153, in write_code_node_to_file
    format_result = style_format.auto_format(rendered_text, filename=filepath)
  File "/scratch/chromium_build/chromium/src/third_party/blink/renderer/bindings/scripts/bind_gen/style_format.py", line 54, in auto_format
    return clang_format(contents, filename)
  File "/scratch/chromium_build/chromium/src/third_party/blink/renderer/bindings/scripts/bind_gen/style_format.py", line 62, in clang_format
    return _invoke_format_command(command_line, filename, contents)
  File "/scratch/chromium_build/chromium/src/third_party/blink/renderer/bindings/scripts/bind_gen/style_format.py", line 75, in _invoke_format_command
    command_line, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
````



i hope it aint so, because prebuilt bins in SOURCE is  beyond all i can buy.

**Comment by flynn1973** [comment]
unbelievable...

````
root@lpgaixmgmtlx01:/scratch/chromium_build/chromium/src/buildtools/linux64>file gn
gn: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, stripped
root@lpgaixmgmtlx01:/scratch/chromium_build/chromium/src/buildtools/linux64>file *
clang-format:      ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped
clang-format.sha1: ASCII text, with no line terminators
gn:                ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, stripped
````

**Comment by flynn1973** [comment]
after a lot off fiddling, manual patch applying, header and script editing chromium built successfully. not the most satisfying experience to be honest.
however, thank you for your help.

````
root@lpgaixmgmtlx01:/scratch/chromium_build/chromium/src/out/Default>./chrome --version
Chromium 82.0.4051.0
````

**Comment by llebout** [comment]
@flynn1973 Yes, Google's build system is quite depressing. However, we've got everything working over there: https://gitlab.com/chromium-ppc64le/chromium-ppc64le
Using these scripts directly should allow you to compile for RHEL with minimal modification if any.
The patches are most tested on stable Chromium releases, not latest HEAD. 

EDIT: Sorry, I thought you didnt have it working, glad it worked for you! :)
